--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "PORTFOLIO"."USER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table USER_TBL
--------------------------------------------------------

  CREATE TABLE "PORTFOLIO"."USER_TBL" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(30 BYTE), 
	"USER_NICKNAME" VARCHAR2(15 BYTE), 
	"USER_NAME" VARCHAR2(10 BYTE), 
	"USER_AGE" NUMBER, 
	"USER_GENDER" VARCHAR2(3 BYTE), 
	"USER_PHONE" VARCHAR2(11 BYTE), 
	"USER_ENROLLDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PORTFOLIO.USER_TBL
SET DEFINE OFF;
Insert into PORTFOLIO.USER_TBL (USER_ID,USER_PW,USER_NICKNAME,USER_NAME,USER_AGE,USER_GENDER,USER_PHONE,USER_ENROLLDATE) values ('test01@gmail.com','test01','테스트01','일용자',11,'F','01012123434',to_timestamp('23/08/01 15:28:34.784000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into PORTFOLIO.USER_TBL (USER_ID,USER_PW,USER_NICKNAME,USER_NAME,USER_AGE,USER_GENDER,USER_PHONE,USER_ENROLLDATE) values ('test02@gmail.com','test02','test02','이용자',22,'F','01022558866',to_timestamp('23/08/03 17:21:38.677000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into PORTFOLIO.USER_TBL (USER_ID,USER_PW,USER_NICKNAME,USER_NAME,USER_AGE,USER_GENDER,USER_PHONE,USER_ENROLLDATE) values ('test03@gmail.com','test03','test03','테스트3',33,'M','01023235656',to_timestamp('23/08/07 10:29:00.951000000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index SYS_C007216
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTFOLIO"."SYS_C007216" ON "PORTFOLIO"."USER_TBL" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007217
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTFOLIO"."SYS_C007217" ON "PORTFOLIO"."USER_TBL" ("USER_NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_TBL
--------------------------------------------------------

  ALTER TABLE "PORTFOLIO"."USER_TBL" ADD CONSTRAINT "GENDER_CHECK" CHECK (USER_GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "PORTFOLIO"."USER_TBL" ADD UNIQUE ("USER_NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTFOLIO"."USER_TBL" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTFOLIO"."USER_TBL" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTFOLIO"."USER_TBL" MODIFY ("USER_PW" NOT NULL ENABLE);
